# -*- coding: utf-8 -*-
"""london_weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eosSU7bBpFnx4EeR1lYmOGotbIfj9d4

# London Weather Prediction with MLflow

## Project Objective

In this project, we build Machine Learning models to predict:

- Mean temperature in London, England

using historical weather data.

We also:

- Compare several regression models
- Evaluate performance using RMSE
- Track experiments with MLflow
- Save the best model
- Search all MLflow runs

Goal:
Achieve an RMSE <= 3

Dataset columns:

- cloud_cover
- sunshine
- global_radiation
- max_temp
- min_temp
- precipitation
- pressure
- snow_depth

Target:
- mean_temp

1. Import Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import sys
!{sys.executable} -m pip install mlflow

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor
)

from xgboost import XGBRegressor

import joblib
import mlflow
import mlflow.sklearn

import warnings
warnings.filterwarnings("ignore")

"""2. Load Dataset"""

weather = pd.read_csv("/content/sample_data/london_weather.csv")

# Display first rows
weather.head()

"""3. Inspect Dataset"""

print("Dataset Shape:")
print(weather.shape)

print("\nDataset Info:")
weather.info()

print("\nMissing Values:")
print(weather.isnull().sum())

print("\nStatistical Summary:")
weather.describe()

"""4. Data Cleaning"""

# Remove duplicates
weather = weather.drop_duplicates()

# Convert date column
weather["date"] = pd.to_datetime(
    weather["date"],
    format="%Y%m%d"
)

# Extract useful date features
weather["year"] = weather["date"].dt.year
weather["month"] = weather["date"].dt.month
weather["day"] = weather["date"].dt.day

# Handle missing values in target variable 'mean_temp'
weather.dropna(subset=['mean_temp'], inplace=True)

"""5. Exploratory Data Analysis"""

plt.figure(figsize=(10, 5))
sns.histplot(weather["mean_temp"], bins=30, kde=True)
plt.title("Distribution of Mean Temperature")
plt.show()

plt.figure(figsize=(12, 8))
sns.heatmap(weather.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""6. Feature Selection"""

features = [
    "cloud_cover",
    "sunshine",
    "global_radiation",
    "max_temp",
    "min_temp",
    "precipitation",
    "pressure",
    "snow_depth",
    "year",
    "month",
    "day"
]

target = "mean_temp"

X = weather[features]
y = weather[target]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

"""7. Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

"""8. Preprocessing Pipeline"""

numeric_features = features

numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features)
    ]
)

"""9. Define Models"""

models = {
    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        max_depth=20,
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=5,
        random_state=42
    ),

    "Extra Trees": ExtraTreesRegressor(
        n_estimators=200,
        max_depth=20,
        random_state=42
    ),

    "XGBoost": XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )
}

"""10. Configure MLflow"""

mlflow.set_experiment("London_Weather_Temperature_Prediction")

"""11. Train and Evaluate Models"""

results = []

best_rmse = float("inf")
best_model = None
best_model_name = None

for model_name, model in models.items():

    print(f"\nTraining: {model_name}")

    with mlflow.start_run(run_name=model_name):

        # Build pipeline
        pipeline = Pipeline(
            steps=[
                ("preprocessor", preprocessor),
                ("regressor", model)
            ]
        )

        # Train model
        pipeline.fit(X_train, y_train)

        # Predictions
        y_pred = pipeline.predict(X_test)

        # Metrics
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        mae = mean_absolute_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        # Store results
        results.append({
            "Model": model_name,
            "RMSE": rmse,
            "MAE": mae,
            "R2": r2
        })

        # Print metrics
        print("RMSE:", round(rmse, 4))
        print("MAE:", round(mae, 4))
        print("R2:", round(r2, 4))

"""Log Parameters"""

mlflow.log_param("model_name", model_name)

if hasattr(model, "n_estimators"):
    mlflow.log_param("n_estimators", model.n_estimators)

if hasattr(model, "max_depth"):
    mlflow.log_param("max_depth", model.max_depth)

if hasattr(model, "learning_rate"):
    mlflow.log_param("learning_rate", model.learning_rate)

"""Log Metrics
        IMPORTANT: include "rmse" in metric name
"""

mlflow.log_metric("rmse_score", rmse)
mlflow.log_metric("mae_score", mae)
mlflow.log_metric("r2_score", r2)

"""Log Model"""

mlflow.sklearn.log_model(
            sk_model=pipeline,
            artifact_path="model"
        )

"""Save Best Model"""

if rmse < best_rmse:
            best_rmse = rmse
            best_model = pipeline
            best_model_name = model_name

"""12. Model Comparison Results"""

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="RMSE",
    ascending=True
)

print("\nModel Comparison:")
print(results_df)

"""13. Visualize Model Performance"""

plt.figure(figsize=(10, 5))

sns.barplot(
    data=results_df,
    x="Model",
    y="RMSE"
)

plt.axhline(3, color="red", linestyle="--", label="Target RMSE = 3")

plt.title("Model RMSE Comparison")
plt.xticks(rotation=20)
plt.legend()
plt.show()

"""14. Best Model"""

print("\nBest Model:", best_model_name)
print("Best RMSE:", round(best_rmse, 4))

"""15. Save Best Model"""

joblib.dump(
    best_model,
    "best_london_weather_model.pkl"
)

print("\nBest model saved successfully.")

"""16. Predict New Weather Example"""

new_weather = pd.DataFrame({
    "cloud_cover": [5],
    "sunshine": [6.5],
    "global_radiation": [55],
    "max_temp": [18],
    "min_temp": [9],
    "precipitation": [1.2],
    "pressure": [101500],
    "snow_depth": [0],
    "year": [2025],
    "month": [6],
    "day": [15]
})

prediction = best_model.predict(new_weather)

print("\nPredicted Mean Temperature:")
print(round(prediction[0], 2), "°C")

"""17. Search All MLflow Runs"""

experiment = mlflow.get_experiment_by_name(
    "London_Weather_Temperature_Prediction"
)

experiment_results = mlflow.search_runs(
    experiment_ids=[experiment.experiment_id]
)

print("\nMLflow Experiment Results:")
print(experiment_results)

"""18. Save MLflow Results"""

experiment_results.to_csv(
    "mlflow_experiment_results.csv",
    index=False
)

print("\nMLflow results saved successfully.")

"""19. Feature Importance (Tree Models)"""

if hasattr(best_model.named_steps["regressor"], "feature_importances_"):

    importance = best_model.named_steps[
        "regressor"
    ].feature_importances_

    importance_df = pd.DataFrame({
        "Feature": features,
        "Importance": importance
    }).sort_values(
        by="Importance",
        ascending=False
    )

    plt.figure(figsize=(10, 6))

    sns.barplot(
        data=importance_df,
        x="Importance",
        y="Feature"
    )

    plt.title("Feature Importance")
    plt.show()

"""20. Final Conclusion

In this project, we:

- Loaded and cleaned London weather data
- Performed exploratory data analysis
- Built multiple regression models
- Evaluated models using RMSE, MAE, and R²
- Logged experiments using MLflow
- Saved the best model
- Retrieved all MLflow runs

Goal:
Predict mean temperature with RMSE <= 3

MLflow tracking included:
- Model parameters
- RMSE metrics
- Saved trained models
- Experiment history
"""